Build lockc on OpenStack with openSUSE Leap image
rancher-sandbox/lockc pull request #99
Opened 2021-11-22 13:55 UTC by mjura

2021-11-22 15:11 UTC, vadorovsky commented on contrib/terraform/libvirt/worker.tf
> +    script = "provision-k8s-containerd-cp.sh"
Change it back pls, cp = master

2021-11-22 17:10 UTC, vadorovsky requested changes
OpenStack changes look good, but please remove the change in `libvirt` dir

2021-11-23 10:09 UTC, mjura commented on contrib/terraform/libvirt/worker.tf
> +    script = "provision-k8s-containerd-cp.sh"
you are right, removed

2021-11-23 11:21 UTC, vadorovsky approved these changes

2021-11-23 11:21 UTC, merged